### PR TITLE
Add all decks option

### PR DESCRIPTION
**Pull request by MarvNC**
This option allows you to create a kanji grid from all the decks in your collection.

anki_Anki_2022-10-19_00-22-07

### CODE REVIEW

**Comment by spfaus** [comment]
Looks like a nice addition IMHO.
I just see a small usability problem with needing (somewhat) matching fields in multiple decks that contain the relevant kanji.

**Comment by MarvNC** [comment]
Yeah, I have quite a few things in my pattern now for all my decks. I guess kanji grid could be made to look at the card template to see which fields are on the front of the card.

`kanji expression vocabulary-kanji radical entry vocab-hanja simplified traditional character front 漢字`

**Comment by spfaus** [comment]
I didn't know you could just list them, that makes it much more manageable.

**Comment by MarvNC** [comment]
Broken in latest Anki versions, haven't had the time to figure it out.

**Pull request closed without merging**
